/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as BuyingGuideIndexRouteImport } from './routes/buying-guide/index'
import { Route as ProductPostIdRouteImport } from './routes/product/$postId'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyingGuideIndexRoute = BuyingGuideIndexRouteImport.update({
  id: '/buying-guide/',
  path: '/buying-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductPostIdRoute = ProductPostIdRouteImport.update({
  id: '/product/$postId',
  path: '/product/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/product/$postId': typeof ProductPostIdRoute
  '/buying-guide': typeof BuyingGuideIndexRoute
  '/compare': typeof CompareIndexRoute
  '/deals': typeof DealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/product/$postId': typeof ProductPostIdRoute
  '/buying-guide': typeof BuyingGuideIndexRoute
  '/compare': typeof CompareIndexRoute
  '/deals': typeof DealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/product/$postId': typeof ProductPostIdRoute
  '/buying-guide/': typeof BuyingGuideIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/i18n'
    | '/product/$postId'
    | '/buying-guide'
    | '/compare'
    | '/deals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/i18n'
    | '/product/$postId'
    | '/buying-guide'
    | '/compare'
    | '/deals'
  id:
    | '__root__'
    | '/'
    | '/demo/i18n'
    | '/product/$postId'
    | '/buying-guide/'
    | '/compare/'
    | '/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoI18nRoute: typeof DemoI18nRoute
  ProductPostIdRoute: typeof ProductPostIdRoute
  BuyingGuideIndexRoute: typeof BuyingGuideIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  DealsIndexRoute: typeof DealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buying-guide/': {
      id: '/buying-guide/'
      path: '/buying-guide'
      fullPath: '/buying-guide'
      preLoaderRoute: typeof BuyingGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$postId': {
      id: '/product/$postId'
      path: '/product/$postId'
      fullPath: '/product/$postId'
      preLoaderRoute: typeof ProductPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoI18nRoute: DemoI18nRoute,
  ProductPostIdRoute: ProductPostIdRoute,
  BuyingGuideIndexRoute: BuyingGuideIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  DealsIndexRoute: DealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
