/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleBrandsRouteImport } from './routes/$locale/brands'
import { Route as LocaleDealsIndexRouteImport } from './routes/$locale/deals/index'
import { Route as LocaleCompareIndexRouteImport } from './routes/$locale/compare/index'
import { Route as LocaleBuyingGuideIndexRouteImport } from './routes/$locale/buying-guide/index'
import { Route as LocaleProductPostIdRouteImport } from './routes/$locale/product/$postId'
import { Route as LocaleDemoI18nRouteImport } from './routes/$locale/demo.i18n'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBrandsRoute = LocaleBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDealsIndexRoute = LocaleDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleCompareIndexRoute = LocaleCompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBuyingGuideIndexRoute = LocaleBuyingGuideIndexRouteImport.update({
  id: '/buying-guide/',
  path: '/buying-guide/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProductPostIdRoute = LocaleProductPostIdRouteImport.update({
  id: '/product/$postId',
  path: '/product/$postId',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDemoI18nRoute = LocaleDemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/brands': typeof LocaleBrandsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/demo/i18n': typeof LocaleDemoI18nRoute
  '/$locale/product/$postId': typeof LocaleProductPostIdRoute
  '/$locale/buying-guide': typeof LocaleBuyingGuideIndexRoute
  '/$locale/compare': typeof LocaleCompareIndexRoute
  '/$locale/deals': typeof LocaleDealsIndexRoute
}
export interface FileRoutesByTo {
  '/$locale/brands': typeof LocaleBrandsRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/demo/i18n': typeof LocaleDemoI18nRoute
  '/$locale/product/$postId': typeof LocaleProductPostIdRoute
  '/$locale/buying-guide': typeof LocaleBuyingGuideIndexRoute
  '/$locale/compare': typeof LocaleCompareIndexRoute
  '/$locale/deals': typeof LocaleDealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/brands': typeof LocaleBrandsRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/demo/i18n': typeof LocaleDemoI18nRoute
  '/$locale/product/$postId': typeof LocaleProductPostIdRoute
  '/$locale/buying-guide/': typeof LocaleBuyingGuideIndexRoute
  '/$locale/compare/': typeof LocaleCompareIndexRoute
  '/$locale/deals/': typeof LocaleDealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/brands'
    | '/$locale/'
    | '/$locale/demo/i18n'
    | '/$locale/product/$postId'
    | '/$locale/buying-guide'
    | '/$locale/compare'
    | '/$locale/deals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale/brands'
    | '/$locale'
    | '/$locale/demo/i18n'
    | '/$locale/product/$postId'
    | '/$locale/buying-guide'
    | '/$locale/compare'
    | '/$locale/deals'
  id:
    | '__root__'
    | '/$locale'
    | '/$locale/brands'
    | '/$locale/'
    | '/$locale/demo/i18n'
    | '/$locale/product/$postId'
    | '/$locale/buying-guide/'
    | '/$locale/compare/'
    | '/$locale/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/brands': {
      id: '/$locale/brands'
      path: '/brands'
      fullPath: '/$locale/brands'
      preLoaderRoute: typeof LocaleBrandsRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/deals/': {
      id: '/$locale/deals/'
      path: '/deals'
      fullPath: '/$locale/deals'
      preLoaderRoute: typeof LocaleDealsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/compare/': {
      id: '/$locale/compare/'
      path: '/compare'
      fullPath: '/$locale/compare'
      preLoaderRoute: typeof LocaleCompareIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/buying-guide/': {
      id: '/$locale/buying-guide/'
      path: '/buying-guide'
      fullPath: '/$locale/buying-guide'
      preLoaderRoute: typeof LocaleBuyingGuideIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/product/$postId': {
      id: '/$locale/product/$postId'
      path: '/product/$postId'
      fullPath: '/$locale/product/$postId'
      preLoaderRoute: typeof LocaleProductPostIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/demo/i18n': {
      id: '/$locale/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/$locale/demo/i18n'
      preLoaderRoute: typeof LocaleDemoI18nRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleBrandsRoute: typeof LocaleBrandsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleDemoI18nRoute: typeof LocaleDemoI18nRoute
  LocaleProductPostIdRoute: typeof LocaleProductPostIdRoute
  LocaleBuyingGuideIndexRoute: typeof LocaleBuyingGuideIndexRoute
  LocaleCompareIndexRoute: typeof LocaleCompareIndexRoute
  LocaleDealsIndexRoute: typeof LocaleDealsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleBrandsRoute: LocaleBrandsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleDemoI18nRoute: LocaleDemoI18nRoute,
  LocaleProductPostIdRoute: LocaleProductPostIdRoute,
  LocaleBuyingGuideIndexRoute: LocaleBuyingGuideIndexRoute,
  LocaleCompareIndexRoute: LocaleCompareIndexRoute,
  LocaleDealsIndexRoute: LocaleDealsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
